version: '3'

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: node-${PROJECT_NAME}
        ports:
            - 80
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./app:/var/www/html
        env_file:
        - ./.env.local
        entrypoint: /entrypoint.sh

volumes:
    data-volume: {}
